# Generated by Django 5.0.6 on 2025-09-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationsession',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
