services:
  - type: web
    name: curriculos-ia
    env: python
    plan: free
    pythonVersion: "3.11"          # Define a versão do Python
    buildCommand: "./build.sh"
    startCommand: "gunicorn curriculos_ia.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
