services:
  - type: web
    name: curriculos-ia
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: "gunicorn curriculos_ia.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
